apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiransai359-deploy
  labels:
    app: kiransai359-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: kiransai359-app
  template:
    metadata:
      labels:
        app: kiransai359-app
    spec:
      containers:
      - name: kiransai359-container
        image: kiransai359/pl-bankjavawebappimg
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: kiransai359-np-service
  namespace: qa
  labels:
    app: kiransai359-app
spec:
  selector:
    app: kiransai359-app
  type: NodePort
  ports:
  - nodePort: 31028
    port: 8082
    targetPort: 8082
